version: "2"

run:
  allow-parallel-runners: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    godot:
      scope: all
      capital: false
    goheader:
      template: |-
        Copyright 2024.

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    importas:
      no-unaliased: true
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        - pkg: sigs.k8s.io/cluster-api/api/v1beta1
          alias: clusterv1
        - pkg: sigs.k8s.io/cluster-api/exp/ipam/api/v1beta1
          alias: ipamv1
        - pkg: github.com/ubiquiti-community/cluster-api-ipam-provider-unifi/api/v1alpha1
          alias: ipamv1alpha1
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      rules:
        - name: comment-spacings
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocognit
          - goconst
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - all
        path: zz_generated\.deepcopy\.go
      - linters:
          - revive
        path: internal/webhooks/.*_webhook\.go
        text: Function 'SetupWebhookWithManager' is too long
    paths:
      - third_party
      - builtin
      - examples

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/ubiquiti-community/cluster-api-ipam-provider-unifi)
        - prefix(sigs.k8s.io/cluster-api)
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/ubiquiti-community/cluster-api-ipam-provider-unifi
  exclusions:
    generated: lax
    paths:
      - third_party
      - builtin
      - examples

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
